volumes:
  data1:
  data2:
  data3:

services:
  backend1:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: python-blockchain-backend
    environment:
      FLASK_RUN_PORT: 8000
      DATA_FILE: /data/chain.json
    network_mode: "host"
    volumes:
      - "data1:/data"
  backend2:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: python-blockchain-backend
    environment:
      FLASK_RUN_PORT: 8001
      DATA_FILE: /data/chain.json
    network_mode: "host"
    volumes:
      - "data2:/data"
  backend3:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: python-blockchain-backend
    environment:
      FLASK_RUN_PORT: 8002
      DATA_FILE: /data/chain.json
    network_mode: "host"
    volumes:
      - "data3:/data"
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: python-blockchain-frontend
    environment:
      FLASK_RUN_PORT: 5000
    network_mode: "host"
